### ISSUE TITLE
Sort demographics into profiles

### ISSUE THREAD

**Issue by 14corman** [14corman/JMIProject#12]
You can group by state, country, region, etc. You also have groups for gender or ages if need be. You will need to make these groups and ID them. This will be used later for analysis.

It would be a good idea to make an excel sheet with the groups and their IDs so the preprocess python program can read it and sort the data out later.

**Comment by 14corman** [comment]
This can be updated now to be more specific. When building demographic categories, you will need 3:
1. location category that can be grouped in a few different ways
2. sex (male, female)
3. age (need to be brought into groups such as 0-20)

We will use the R(1), I(2), and S(3) values as the standardized MIC value when doing testing.

**Comment by 14corman** [comment]
So, for parts 2 and 3 above, here are the histograms (with respective boxings) for sex and age data:

![image](https://user-images.githubusercontent.com/15676385/54443413-910a5b00-470e-11e9-9bae-7d7fa95ea515.png)

For the gender graph, 1 = Male and 0 = Female. We have about an equal number of males and females in the dataset, so I do not see this being helpful. However, I will still test it later.

![image](https://user-images.githubusercontent.com/15676385/54443160-117c8c00-470e-11e9-9be4-0f426d1bb742.png)

**Comment by 14corman** [comment]
Here is the locations by Site code:
![image](https://user-images.githubusercontent.com/15676385/54444898-aa60d680-4711-11e9-8cce-34b09e9b3c3a.png)


Values are:
X | Y
2 | 35
3 | 62
4 | 28
12 | 18
13 | 27
15 | 225
17 | 45
21 | 70
24 | 77
25 | 43
27 | 34
30 | 34
39 | 37
40 | 31
43 | 13
46 | 46
48 | 72
49 | 7
51 | 32
52 | 55
57 | 36
62 | 50
63 | 12
64 | 29
65 | 30
66 | 47
68 | 84
69 | 74
75 | 33
81 | 134
86 | 104
89 | 5
90 | 36
91 | 12
96 | 7
97 | 46
100 | 16
101 | 3
102 | 13
106 | 8
107 | 63
112 | 7
113 | 23
115 | 130
116 | 60
117 | 5
120 | 18
122 | 16
126 | 99
127 | 57
129 | 75
130 | 24
131 | 22
133 | 21
134 | 38
136 | 81
137 | 38
138 | 35
139 | 43
146 | 49
148 | 2
149 | 16
150 | 27
203 | 14
215 | 34
219 | 29
229 | 14
260 | 15
262 | 2
263 | 14
277 | 11
279 | 7
280 | 8
281 | 4
283 | 5
302 | 20
303 | 14
307 | 21
317 | 73
329 | 10
333 | 46
336 | 17
342 | 67
346 | 46
347 | 3
349 | 1
361 | 1
364 | 2
365 | 18
370 | 18
371 | 29
376 | 20
377 | 62
379 | 5
380 | 1
404 | 35
410 | 25
411 | 8
412 | 22
413 | 11
417 | 6
420 | 19
422 | 48
425 | 17
426 | 19
433 | 22
437 | 42
442 | 34
443 | 13
448 | 28
452 | 36
453 | 16
454 | 8
455 | 9
456 | 4
457 | 13
460 | 8
461 | 4
462 | 7
464 | 16
467 | 32
468 | 36
469 | 11
470 | 34
471 | 4
472 | 24
473 | 7
475 | 21
476 | 16
477 | 9
480 | 16
481 | 43
601 | 49
603 | 82
605 | 47
606 | 27
614 | 30
616 | 72
703 | 12
704 | 7
721 | 7
726 | 1
728 | 36
732 | 5
734 | 16
739 | 7
742 | 10
760 | 7
789 | 13
792 | 22
794 | 7
800 | 57
806 | 12
810 | 41
812 | 3
814 | 9
815 | 19

**Comment by ewalserk** [comment]
I know I said I would have the MIC stuff done over the weekend but it turned out to be a much bigger task than I was anticipating, I should have it done by today, I hope it's not too late, there was just a lot more drugs than I thought originally.

**Comment by ewalserk** [comment]
Hopefully I didn't repeat someone else's work, but I cleaned the data as they wanted (0.049 ->0.05, 8.1 -> 8 etc), created the SIR, categories for each drug, and created the genetic profiles that they requested (neither = 0, 1 = ESBL, 2 = Carbapenemase, 3 = Both) and then did a Chi-Squared test for independence to check if the genetic profiles are independent of continent, which yielded a p-value of basically 0, which means that broad geographic location is probably not independent of what types of resistance profiles are being exhibited.

**Comment by 14corman** [comment]
Here are a few things:

1. We already had all this. If you would look at issues, or come to meetings then you would know what we have and do not have already done

2. Look at what this issue wants. It does not want all of this. I did everything above in Excel in less than 20 minutes. I just need to get a the states sorted to see what we have there and this issue is done.

3. Once this was all figured out, we were going to put in the information found from this into the preprocess python file and output all formatted data into an excel sheet (another issue you could have looked at).

4. NOW you can just do any tests you want on that excel sheet in a matter of an hour or so.

From what you did:
1. clean data: did not need to do this
2. categories: already done in preprocess
3. genetic profiles: have no idea why you did this, but was already done in preprocess
4. we never talked about continent, and we were not doing genetic profiles but SIR categories.
5. we were going to do what I put up above.

You have had multiple weeks to do this one thing. I even tried giving you a few chances to meet with me and get caught up since you said you were sick at the start. For now, since we now have the boxing information from this issue (besides states that I may be able to get to today) you can just wait until we get to needing tests from the excel sheet. This will come from the following: follow the other [issue](https://github.com/14corman/JMIProject/issues/11) to see when that is done and the excel sheet is available. When it is, you can look at this [issue](https://github.com/14corman/JMIProject/issues/14) to see what is available in the excel sheet, and what data needs to be tested with what other data.

You were supposed to do what I did above weeks ago, and we could not wait for you any longer. Now the only thing left for you to do is to do the tests on the outputed excel sheet later. You will only have at most a week to do that since we waited so long for this.

**Comment by 14corman** [comment]
I am about to post the bins for the State locations, but I just saw this feature in excel and wanted to post it here.

![image](https://user-images.githubusercontent.com/15676385/54478883-2f68f000-47e5-11e9-860c-6e7a26206cc0.png)

This shows all the locations that we have data for (based on state). What is interesting from this is that we are counting some Austrailian states as states in here, and we are missing 2073 points from other countries.

**Comment by 14corman** [comment]
![image](https://user-images.githubusercontent.com/15676385/54478930-ccc42400-47e5-11e9-92b2-395190ce21a0.png)

![image](https://user-images.githubusercontent.com/15676385/54478943-0dbc3880-47e6-11e9-83ec-4fbf728d8f66.png)


Actual Data:

State | Count
CA | 184
UT | 32
IN | 44
NJ | 166
DE | 7
KY | 104
TX | 213
NY | 441
MI | 70
OH | 75
WA | 105
IL | 62
AK | 4
VA | 46
Other countries (blank)  | 2073
PA | 51
FL | 95
OR | 42
AR | 5
GA | 20
Jaliso | 130
CO | 48
LA | 28
TN | 22
MO | 33
MA | 117
NC | 24
VT | 16
MN | 49
NE | 18
AL | 12
VIC | 30
IA | 13
Western Australia | 21
Dgo | 99
WI | 47
AZ | 44
ME | 9
QLD | 14
NM | 13
MD | 7
KS | 17
New South Wales | 14
ND | 7
