### ISSUE TITLE
Do all analysis needed from preprocessed data

### ISSUE THREAD

**Issue by 14corman** [14corman/JMIProject#14]
Do any and all analysis needed between demographic data and MIC values.

This may turn into more analysis after we hear back from Ryan or Catlin, but for now we will focus on this analysis.

**Comment by 14corman** [comment]
I have made the preprocess python file export an excel sheet with all needed formatted data. This file has been made and is provided in this repository with the name **"formated data.xlsx"**. If you would like to know where the columns and numbers are coming from, here is a snippet from the file:
![image](https://user-images.githubusercontent.com/15676385/54494911-1297ef80-48ad-11e9-91e9-d46d0b532f7e.png)

The first 4 columns are self explanatory. The last 4 are the respective sums for the drugs of the subject. For example, row 2 shows a subject that has 8 drugs that are "MIC num undefined". This means the subject has 8 drugs that are not part of the beta-lactamase category, and would get a 0 in the dataset. The next 3 columns follow the same with R, I, and S.

The binnings for the first 4 columns can be found [here](https://github.com/14corman/JMIProject/issues/12) or in the preprocess.py file. The numbers for site and state are the index into the arrays found in the file. So, subject in row 2 has site ID of 59 which corresponds with site number 139. Their state Id is 4 which means their state they are in is California (CA). Their gender is 0 (M), and their Age Id is 15 which is between 75 and 80 years old.

State values that are -1 are subjects that do are in a country without states.

@ewalserk if you have any further questions please post them here, or email the group and we can answer them for you. The tests will be to see if any of the first 4 columns are dependent on any (or all) of the NA, R, I, or S columns. If they are dependent, you can find the R^2 value in excel to see how much they correlate.

**Comment by ewalserk** [comment]
[Demographics Report.docx](https://github.com/14corman/JMIProject/files/3010984/Demographics.Report.docx)

I have looked at the formated data.xlsx file and found that age slightly but meaningfully affects S and R values and site/state affect undefined/S/R values but the relationship between site and these values is clearer than that for state.

Gender doesn't affect S/R enough to warrant being considered important for further analysis.

Details can be found in the attached document.

**Comment by 14corman** [comment]
The file and work looks incredible@ewalserk. Would you be able to commit your Report to the repository?

I will see who should put Age and Site in as data into an updated model. 

Do you think there is anything we should do to the data itself? You mention that age is more R in the middle and more S to the sides. Would it be more beneficial to simply use a boolean rather than the age bin as the variable then to ask whether the bin is in the middle 4-17 or not? I think we site we can just leave it as is. 

We will use all of that information in that document as well as that table in the paper when we start writing it this week. I will talk more about it at Thursday's meeting.
